// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvHOU6GYyyg5e-bH0sEibGuHpd1SskO1M',
    appId: '1:670489290166:web:adfa367bc1d43993988d17',
    messagingSenderId: '670489290166',
    projectId: 'deneme-proje-24929',
    authDomain: 'deneme-proje-24929.firebaseapp.com',
    storageBucket: 'deneme-proje-24929.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQBhitlZ2NX6uX_EmuEjc1Hl8OfsYaWzw',
    appId: '1:670489290166:android:bfa51248d81ca34c988d17',
    messagingSenderId: '670489290166',
    projectId: 'deneme-proje-24929',
    storageBucket: 'deneme-proje-24929.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbSvuD-ibMVq1QoULQjlX2amHcuTWw7ao',
    appId: '1:670489290166:ios:976a15eba3cd85f1988d17',
    messagingSenderId: '670489290166',
    projectId: 'deneme-proje-24929',
    storageBucket: 'deneme-proje-24929.appspot.com',
    iosBundleId: 'com.example.toplulukProje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbSvuD-ibMVq1QoULQjlX2amHcuTWw7ao',
    appId: '1:670489290166:ios:976a15eba3cd85f1988d17',
    messagingSenderId: '670489290166',
    projectId: 'deneme-proje-24929',
    storageBucket: 'deneme-proje-24929.appspot.com',
    iosBundleId: 'com.example.toplulukProje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvHOU6GYyyg5e-bH0sEibGuHpd1SskO1M',
    appId: '1:670489290166:web:c76500e1d651ec60988d17',
    messagingSenderId: '670489290166',
    projectId: 'deneme-proje-24929',
    authDomain: 'deneme-proje-24929.firebaseapp.com',
    storageBucket: 'deneme-proje-24929.appspot.com',
  );
}
